<?php

    $birthday = new DateTime('1990-07-03');
    $today = new DateTime('now');
    $age = $today->diff($birthday)->y;

?>

<div class="container container-fluid">
    <div class="row container-fluid d-flex justify-content-center">
        <div class="col-8">
            <div class="row">
                <div class="col-12 col-md-6 order-0 order-md-0 container-img-avatar">
                    <img src="../images/aboutme/avatar.png" class="img-avatar-aboutme">
                </div>
                <div class="col-12 col-md-6 order-1 order-md-1 container-descr-avatar">
                    <p class="descr-avatar-aboutme" id="descr-avatar-one">Olá! Eu sou o Lucas e tenho <?= $age ?> anos. Sou desenvolvedor Full-Stack, com sólida experiência em análise e desenvolvimento de sistemas e gestão estratégica de pessoas.</p>
                    <p class="descr-avatar-aboutme" id="descr-avatar-two">Eu tenho uma extensiva experiência com JavaScript (Angular e ReactJS), Dart (Flutter), FlutterFlow, Typescript, PHP 7 (Laravel), IONIC, Bootstrap 5.3 e SASS, e estou disposto a aprender inovações criativas e soluções funcionais. Estou sempre procurando novos desafios e aprendendo tecnologias para continuar a enriquecer minhas habilidades e entregar um resultado de melhor qualidade possível. Sinta-se a vontade para explorar meu <a href="portfolio" class="link-aboutme">portfólio</a> e veja meus últimos projetos.</p>
                </div>
                <div class="col-12 col-md-6 order-2 order-md-2 container-social-network d-flex justify-content-around">
                    <a href="https://www.linkedin.com/in/lucas-carvalho-b7b506b5/" target="_blank">
                        <img src="../images/aboutme/linkedin.png" alt="linkedin" class="img-social-network">
                    </a>
                    <a href="https://github.com/LucasCarvalho23" target="_blank">
                        <img src="../images/aboutme/github.png" alt="github" class="img-social-network">
                    </a>
                    <a href="../files/LucasCarvalhodaSilva.pdf" download="LucasCarvalhodaSilva.pdf">
                        <img src="../images/aboutme/cv.png" alt="curriculo" class="img-social-network">
                    </a>
                    <a href="https://wa.me/5521965488728?text=Olá%2C%20vi%20seu%20anúncio.%20Gostaria%20de%20fazer%20um%20orçamento" target="_blank">
                        <img src="../images/aboutme/logo-wpp.png" alt="whatsapp" class="img-social-network">
                    </a>
                </div>
                <div class="col-12 col-md-6 order-2 order-md-2 container-social-network d-flex justify-content-around">
                    <img src="../images/aboutme/snake.gif" alt="snake gif" class="gif-social-network">
                </div>
            </div>
        </div>
    </div>
</div>
