<div class="container container-fluid container-home border">
    <div class="row d-flex justify-content-center">
        <div class="col-3 container-info-home">
            <p class="p-first-home" id="p-first-home">Hey! I'm Lucas Carvalho</p>
            <p class="p-second-home" id="p-second-home">but you can call me Lucas</p>
            <p class="p-third-home" id="p-third-home">I'm Full-Stack development</p>
            <p>
                <a href="portfolio">→ <span id="span-see-my-projects">See my projects</span></a>
            </p>
            <p>
                <a href="aboutme">→ <span id="span-see-my-curriculum">See my curriculum</span></a>
            </p>
            <h5 class="mt-5" id="contact-home">Do you want to get a budget to get your website / system up and running?</h5>
            <p>
                <button class="btn btn-success mt-3"><a href="https://wa.me/5521965488728?text=Olá%2C%20vi%20seu%20anúncio.%20Gostaria%20de%20fazer%20um%20orçamento" target="_blank" class="a-index text-light"><span id="contact-me">Contact me</span></a></button>
            </p>
        </div>
    </div>
</div>