<div class="container container-fluid container-home border">
    <div class="row d-flex justify-content-center">
        <div class="col-3 container-info-home">
            <p class="p-first-home">Hey! I'm Lucas Carvalho</p>
            <p class="p-second-home">but you can call me Lucas</p>
            <p class="p-third-home">I'm Full-Stack development</p>
            <p>
                <a href="portfolio">→ See my projects</a>
            </p>
            <p>
                <a href="aboutme">→ See my curriculum</a>
            </p>
        </div>
    </div>
</div>