<div class="container container-fluid container-login">
    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <form action="">
                <input type="text" class="form-control mb-3 input-login" placeholder="Login">
                <input type="password" class="form-control mb-5 input-login" placeholder="Password">
                <div class="d-grid gap-2">
                    <button class="btn btn-outline-primary mb-2">Login in</button>
                </div>
                <div class="d-flex justify-content-between">
                    <a href="/login" class="forgot-password">I forgot my password</a>
                    <span class="text-danger invalid-login">Invalid login and password</span>
                </div>
           </form>
        </div>
    </div>
</div>