<div class="container container-fluid container-login">
    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <form action="/timelineadm" method="post">
                <input type="text" name="login" class="form-control mb-3 input-login" placeholder="Login" required>
                <input type="password" name="password" class="form-control mb-5 input-login" placeholder="Password" required>
                <div class="d-grid gap-2">
                    <button class="btn btn-outline-primary mb-2" type="submit">Login</button>
                </div>
                <div class="d-flex justify-content-between">
                    <a href="/login" class="forgot-password">I forgot my password</a>
                    <?php if (isset($_GET['error']) && $_GET['error'] == 'authentication') { ?>
                        <span class="text-danger invalid-login">Invalid login and password</span>
                    <?php } ?>
                </div>
           </form>
        </div>
    </div>
</div>