<div class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Carousel -->
                <div id="carouselExampleIndicators" class="carousel slide">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3" aria-label="Slide 4"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="4" aria-label="Slide 5"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="5" aria-label="Slide 6"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="#" class="d-block w-100" id="img-portfolio01" title="btec">
                        </div>
                        <div class="carousel-item">
                            <img src="#" class="d-block w-100" id="img-portfolio02" title="escudo">
                        </div>
                        <div class="carousel-item">
                            <img src="#" class="d-block w-100" id="img-portfolio03" title="gn">
                        </div>
                        <div class="carousel-item">
                            <img src="#" class="d-block w-100" id="img-portfolio04" title="spotify">
                        </div>
                        <div class="carousel-item">
                            <img src="#" class="d-block w-100" id="img-portfolio05" title="twitter">
                        </div>
                        <div class="carousel-item">
                            <img src="#" class="d-block w-100" id="img-portfolio06" title="starplus">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="container-img">
        <div class="container">
            <div class="row">
                <div class="d-flex justify-content-center">
                <div class="container-info pt-2 text-center">
                    <p><strong>Project name:</strong> <span id="projectName"><?= isset($this->view->name) ? $this->view->name : 'No project name available'; ?></span></p>
                    <p><strong>Description:</strong> <span id="projectDescription"><?= isset($this->view->description) ? $this->view->description : 'No description available'; ?></span></p>
                    <p><strong>Technologies used:</strong> <span id="projectTechnologies"><?= isset($this->view->technologies) ? $this->view->technologies : 'No technologies available'; ?></span></p>
                    <p><strong>Github repository:</strong> <a class="link-github" href="<?= isset($this->view->github) ? $this->view->github : '#'; ?>" target="_blank"><span>Here</span></a></p>
                    <p><strong>Website hosting:</strong> <a class="link-github" href="<?= isset($this->view->site) ? $this->view->site : '#'; ?>" target="_blank"><span>Here</span></a></p>
                </div>

                </div>
                <div class="col-12 container-images">
                    <div class="row">
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/imgnotfound.png" width="250px" height="250px" class="border-img fixed-img" id="bottom-img-portfolio01">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/imgnotfound.png" width="250px" height="250px" class="border-img fixed-img" id="bottom-img-portfolio02">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/imgnotfound.png" width="250px" height="250px" class="border-img fixed-img" id="bottom-img-portfolio03">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center margin-desktop">
                            <img src="../images/desktop/imgnotfound.png" width="250px" height="250px" class="border-img fixed-img" id="bottom-img-portfolio04">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center margin-desktop">
                            <img src="../images/desktop/imgnotfound.png" width="250px" height="250px" class="border-img fixed-img" id="bottom-img-portfolio05">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center margin-desktop">
                            <img src="../images/desktop/imgnotfound.png" width="250px" height="250px" class="border-img fixed-img" id="bottom-img-portfolio06">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>