<div class="main-content mb-3">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!-- Carousel -->
                <div id="carouselExampleIndicators" class="carousel slide">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="#" class="d-block w-100" id="img-portfolio01">
                        </div>
                        <div class="carousel-item">
                            <img src="#" class="d-block w-100" id="img-portfolio02">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="container-img">
                <div class="d-flex justify-content-center">
                    <div class="col-12 col-sm-6 col-md-4 container-info pt-2 text-center">
                        <p><strong>Project name:</strong> GTEC - Sistema Oficina</p>
                        <p><strong>Description:</strong> Create a portal called Oficina, where employees will fill in information about the works carried out.
                        There will be after the login screen, 4 accessible portals and a Power BI.</p>
                        <p><strong>Technologies used:</strong> PHP7, Bootstrap, SQL and Git</p>
                        <p><strong>Github repository:</strong> <a class="link-github" href="https://github.com/LucasCarvalho23/btec" target="_blank"><span>Here</span></a></p>
                        <p><strong>Website hosting:</strong> In progress</p>
                    </div>
                </div>
                <div class="col-12 container-images">
                    <div class="row">
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/01/btec-main.png" width="300px" class="border-img img-fluid">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/01/btec-login.png" width="300px" class="border-img img-fluid">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/01/btec-main.png" width="300px" class="border-img img-fluid">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/01/btec-login.png" width="300px" class="border-img img-fluid">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/01/btec-main.png" width="300px" class="border-img img-fluid">
                        </div>
                        <div class="col-12 col-sm-6 col-md-4 mb-3 d-flex justify-content-center">
                            <img src="../images/desktop/01/btec-login.png" width="300px" class="border-img img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>