<div class="container container-fluid">
    <div class="row d-flex container-fluid justify-content-center">
        <div class="col-8 container-timeline">
            <div class="row">
                <div class="col-3 ms-4">
                    <img src="../images/timeline/avatar.png" alt="avatar" class="image-avatar">
                </div>
                <div class="col-8 container-bio">
                    <h3>Lucas Carvalho</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore adipisci magnam nobis explicabo dignissimos ratione autem eius libero perspiciatis veniam dolore facere dolorum totam, odio.</p>
                </div>
            </div>
            <div class="row container-posts d-flex justify-content-center">
                <div class="col-10">
                    <hr>
                    <div class="row">
                        <div class="col-3 container-img-individual-post">
                            <img src="../images/timeline/avatar.png" alt="avatar" class="img-individual-post">
                        </div>
                        <div class="col-9 container-content-post">
                            <h5>Lucas Carvalho</h5>
                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut beatae quod nobis quisquam cumque! Maxime voluptas suscipit, nam hic facilis assumenda, ipsum quam non magnam maiores commodi, ipsa vel sunt.</p>
                        </div>
                    </div>
                </div>
                <div class="col-10">
                    <hr>
                    <div class="row">
                        <div class="col-3 container-img-individual-post">
                            <img src="../images/timeline/avatar.png" alt="avatar" class="img-individual-post">
                        </div>
                        <div class="col-9 container-content-post">
                            <h5>Lucas Carvalho</h5>
                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut beatae quod nobis quisquam cumque! Maxime voluptas suscipit, nam hic facilis assumenda, ipsum quam non magnam maiores commodi, ipsa vel sunt.</p>
                        </div>
                    </div>
                </div>
                <div class="col-10">
                    <hr>
                    <div class="row">
                        <div class="col-3 container-img-individual-post">
                            <img src="../images/timeline/avatar.png" alt="avatar" class="img-individual-post">
                        </div>
                        <div class="col-9 container-content-post">
                            <h5>Lucas Carvalho</h5>
                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut beatae quod nobis quisquam cumque! Maxime voluptas suscipit, nam hic facilis assumenda, ipsum quam non magnam maiores commodi, ipsa vel sunt.</p>
                        </div>
                    </div>
                </div>
                <div class="col-10">
                    <hr>
                    <div class="row">
                        <div class="col-3 container-img-individual-post">
                            <img src="../images/timeline/avatar.png" alt="avatar" class="img-individual-post">
                        </div>
                        <div class="col-9 container-content-post">
                            <h5>Lucas Carvalho</h5>
                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut beatae quod nobis quisquam cumque! Maxime voluptas suscipit, nam hic facilis assumenda, ipsum quam non magnam maiores commodi, ipsa vel sunt.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>