<!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- styles -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
      <link rel="stylesheet" href="./css/style.css">
      <link rel="shortcut icon" href="./images/logo.ico" type="image/x-icon">
      <title>Lucas Carvalho - Software Development</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <img src="./images/logo.png" width="50px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav w-100 justify-content-end justify-content-lg-center">
            <li class="nav-item">
              <a class="nav-link underscore" aria-current="page" href="/portfolio" id="portfolio-menu">Portfolio</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link underscore" href="/timeline" id="itsnotablog-menu">It's not a blog</a>
            </li> 
            <li class="nav-item">
              <a class="nav-link underscore" href="/aboutme" id="aboutme-menu">About Me</a>
            </li>
          </ul>

          <div class="d-flex ms-auto justify-content-end justify-content-lg-center me-3">
            <button class="button-lang-icon" onclick="changeLang()">
              <img src="./images/logo-br.png" alt="br" class="lang-icon" id="lang-icon">
            </button>
          </div>  

          <div class="d-flex ms-auto justify-content-end justify-content-lg-center">
            <?php 
              if (isset($this->view->nameuser)) {?>
                <span class="span-welcome"> Hi, <?= $this->view->nameuser ?>, you're welcome!</span>
            <?php } else {?>
              <a href="/login" class="btn btn-outline-primary">Login</a>
            <?php }?>
          </div>
        </div>

      </div>
      <hr>
    </nav>

    <?= $this->content() ?>

    <footer>
      <hr>
      <p>
        <a href="/aboutme">&copy 2024 Lucas Carvalho</a>
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-arrow-up-circle icon-up" id="icon-up" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-7.5 3.5a.5.5 0 0 1-1 0V5.707L5.354 7.854a.5.5 0 1 1-.708-.708l3-3a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 5.707z"/>
        </svg>
      </p>
      
    </footer>

    <!-- script  -->
    <script src="https://cdn-script.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="./javascript/script.js"></script>
  </body>
</html>
